# Generated by Selenium IDE
import pytest
import time
import random, string
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    chrome_options = Options()
    self.driver = webdriver.Chrome()
    #chrome_options.add_argument("user-data-dir=C:/Users/Usuario/AppData/Local/Google/Chrome/User Data")
    #chrome_options.add_argument("profile-directory=Profile 2")
    #self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  ############################## TESTS LOGIN ##############################
  
  def test_login(self):
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
  
  
  ############################## TESTS RECOMENDADOR ##############################
  
  def test_recomendador(self):
    # Se debe iniciar sesión primero
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.set_window_size(974, 1031)
    self.driver.find_element(By.LINK_TEXT, "Recomendador").click()
    
    # Comprueba si aparece el botón "Volver a realizar el test"
    try:
        volver_boton = self.driver.find_element(By.LINK_TEXT, "Volver a realizar el test")
        volver_boton.click()
    except:
        pass  # Si el botón no está presente, continua con el proceso normal

    # Rellenar el formulario
    self.driver.find_element(By.NAME, "question_1").click()
    self.driver.find_element(By.NAME, "question_2").click()
    self.driver.find_element(By.NAME, "question_3").click()
    self.driver.find_element(By.NAME, "question_4").click()
    self.driver.find_element(By.NAME, "question_5").click()
    self.driver.find_element(By.NAME, "question_6").click()
    self.driver.find_element(By.NAME, "question_7").click()
    self.driver.find_element(By.NAME, "question_8").click()
    self.driver.find_element(By.NAME, "question_9").click()
    self.driver.find_element(By.NAME, "question_10").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()  
  
  
  ############################## TESTS FORO ##############################
  
  def generate_unique_suffix(self):
    #Genera un sufijo único aleatorio.
    return ''.join(random.choices(string.ascii_letters + string.digits, k=10))
  
  
  def test_agregarforo(self):
    # Se debe iniciar sesión primero
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
      
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1031)
    self.driver.find_element(By.LINK_TEXT, "Foro").click()
    self.driver.find_element(By.LINK_TEXT, "Agregar Foro").click()
    
    # Generar un nombre único para el foro
    unique_name = f"foro prueba {self.generate_unique_suffix()}"
    
    # Llenar el formulario de creación del foro
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys(unique_name)
    self.driver.find_element(By.ID, "description").send_keys("Descripción del foro prueba")
    self.driver.find_element(By.ID, "category_id").click()
    dropdown = self.driver.find_element(By.ID, "category_id")
    dropdown.find_element(By.XPATH, "//option[. = 'prueba']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    
    # Esperar y verificar el mensaje de éxito
    WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, ".alert-success"))
    )
    success_message = self.driver.find_element(By.CSS_SELECTOR, ".alert-success")
    assert "¡Foro agregado con éxito!" in success_message.text
 
  def test_borrarforo(self):
    # Se debe iniciar sesión primero
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.LINK_TEXT, "Foro").click()
    
    # Esperar a que la tabla esté cargada
    time.sleep(1)
    WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, "table"))
    )
        
    try:
        # Verificar si hay al menos 2 filas en la tabla de foros
        rows = self.driver.find_elements(By.CSS_SELECTOR, "tr")
        if len(rows) < 3:  # La primera fila es el encabezado, por eso < 3
            pytest.skip("No hay suficientes foros para borrar.")
            
        # Intentar hacer clic en el botón de borrar
        delete_button = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) form > .btn")
        delete_button.click()
            
        # Esperar y aceptar el diálogo de confirmación
        WebDriverWait(self.driver, 10).until(EC.alert_is_present())
        alert = self.driver.switch_to.alert
        assert alert.text == "¿Estás seguro de que quieres borrar este foro?"
        alert.accept()
            
        # Esperar a que el mensaje de éxito aparezca
        WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, ".alert-success"))
        )
        
    except Exception as e:
        pytest.fail(f"Test falló con excepción: {e}")
 
 
  def test_editarforo(self):
    # Se debe iniciar sesión primero
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    # Navegar a la página de foros
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1031)
    self.driver.find_element(By.LINK_TEXT, "Foro").click()
    
    # Seleccionar el foro a editar
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td > .btn").click()
    
    # Generar un nombre único
    original_name = "foro cambiado"
    unique_name = f"{original_name} {self.generate_unique_suffix()}"
    
    # Intentar actualizar el nombre del foro
    name_field = self.driver.find_element(By.ID, "name")
    name_field.clear()
    name_field.send_keys(unique_name)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    
    # Esperar y verificar el mensaje de éxito
    WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, ".alert-success"))
    )
    success_message = self.driver.find_element(By.CSS_SELECTOR, ".alert-success")
    assert "¡Foro actualizado con éxito!" in success_message.text
        
      
      
  ############################## TESTS FORO CATEGORÍA ##############################
  
  def test_agregarcategoria(self):
    # Se debe iniciar sesión primero
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    time.sleep(1)
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1031)
    self.driver.find_element(By.LINK_TEXT, "Foro").click()
    
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Agregar Categoría").click()
    
    # Generar un nombre único para la categoría
    unique_name = f"categoría nueva {self.generate_unique_suffix()}"
    
    # Llenar el formulario de creación de categoría
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys(unique_name)
    self.driver.find_element(By.ID, "description").click()
    self.driver.find_element(By.ID, "description").send_keys("Descripción de la nueva categoría")
    
    # Enviar el formulario
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    
    # Esperar y verificar el mensaje de éxito
    WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, ".alert-success"))
    )
    success_message = self.driver.find_element(By.CSS_SELECTOR, ".alert-success")
    assert "¡Categoría agregada con éxito!" in success_message.text
  
  def test_borrarcategoria(self):
    # Se debe iniciar sesión primero
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/?data=root&sort_param=stored")
    self.driver.set_window_size(974, 1031)
    self.driver.find_element(By.LINK_TEXT, "Foro").click()
    
    time.sleep(1)  # Esperar a que se cargue la página

    try:
        self.driver.find_element(By.LINK_TEXT, "Borrar Categoría").click()
        # Esperar a que el botón de borrar esté presente y hacer clic
        delete_button = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, "tr:nth-child(3) .btn"))
        )
        delete_button.click()
        
        # Esperar hasta que la alerta esté presente
        WebDriverWait(self.driver, 10).until(EC.alert_is_present())
        alert = self.driver.switch_to.alert
        
        # Verificar que el mensaje de la alerta sea correcto
        assert alert.text == "¿Estás seguro de que quieres borrar esta categoría?"
        alert.accept()
        
        # Esperar hasta que el mensaje de éxito aparezca
        WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, ".alert-success"))
        )
    
    except Exception as e:
        pytest.fail(f"Test falló con excepción: {e}")
        
        
        
  ############################## TESTS FORO HILO ##############################
  
  def test_agregarhilo(self):
    # Se debe iniciar sesión primero
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    time.sleep(1)
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1031)
    self.driver.find_element(By.LINK_TEXT, "Foro").click()
    
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".table tbody tr:nth-child(2) a").click()
    self.driver.find_element(By.LINK_TEXT, "Agregar Hilo").click()
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys("hilo prueba")
    self.driver.find_element(By.ID, "content").click()
    self.driver.find_element(By.ID, "content").send_keys("hola")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
    # Esperar y verificar el mensaje de éxito
    WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, ".alert-success"))
    )
    success_message = self.driver.find_element(By.CSS_SELECTOR, ".alert-success")
    assert "¡Hilo y comentario añadidos con éxito!" in success_message.text

  def test_borrarhilo(self):
    # Se debe iniciar sesión primero
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1031)
    self.driver.find_element(By.LINK_TEXT, "Foro").click()
    
    # Esperar a que la tabla esté cargada
    WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, "table"))
    )
    
    try:
        # Seleccionar el segundo foro de la lista
        self.driver.find_element(By.CSS_SELECTOR, ".table tbody tr:nth-child(2) a").click()
        
        # Verificar si hay al menos 1 fila en la tabla de hilos
        rows = self.driver.find_elements(By.CSS_SELECTOR, "tr")
        if len(rows) < 2:
            pytest.skip("No hay suficientes hilos para borrar.")
            
        # Intentar hacer clic en el botón de borrar
        delete_button = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) form > .btn")
        delete_button.click()
        
        # Esperar y aceptar el diálogo de confirmación
        WebDriverWait(self.driver, 10).until(EC.alert_is_present())
        alert = self.driver.switch_to.alert
        assert alert.text == "¿Estás seguro de que quieres borrar este hilo?"
        alert.accept()
        
        # Esperar a que el mensaje de éxito aparezca
        WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, ".alert-success"))
        )
        
    except Exception as e:
        pytest.fail(f"Test falló con excepción: {e}")

        
        
  ############################## TESTS FORO COMENTARIO ##############################
  
  def test_agregarcomentario(self):
    # Se debe iniciar sesión primero
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1031)
    self.driver.find_element(By.LINK_TEXT, "Foro").click()
    
    self.driver.find_element(By.CSS_SELECTOR, ".table tbody tr:nth-child(2) a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".table tbody tr:nth-child(1) a").click()
    # Verificar si hay al menos 1 comentario
    comments = self.driver.find_elements(By.CSS_SELECTOR, ".post-box")
    if len(comments) < 1:
        pytest.skip("No hay suficientes comentarios para responder.")
    self.driver.find_element(By.LINK_TEXT, "Responder").click()
    self.driver.find_element(By.ID, "content").click()
    self.driver.find_element(By.ID, "content").send_keys("hola")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
    # Esperar y verificar el mensaje de éxito
    WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, ".alert-success"))
    )
    success_message = self.driver.find_element(By.CSS_SELECTOR, ".alert-success")
    assert "¡Post agregado con éxito!" in success_message.text

  def test_borrarcomentario(self):
    # Se debe iniciar sesión primero
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1031)
    self.driver.find_element(By.LINK_TEXT, "Foro").click()
    
    # Esperar a que los elementos de la lista estén cargados
    WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, ".table tbody"))
    )
    
    try:
        # Seleccionar el segundo foro de la lista
        self.driver.find_element(By.CSS_SELECTOR, ".table tbody tr:nth-child(2) a").click()
        
        # Verificar si hay al menos 1 hilo en la lista de hilos
        WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, ".table tbody"))
        )
        rows = self.driver.find_elements(By.CSS_SELECTOR, ".table tbody tr")
        if len(rows) < 2:
            pytest.skip("No hay suficientes hilos para borrar.")
        
        # Seleccionar el primer hilo de la lista
        self.driver.find_element(By.CSS_SELECTOR, ".table tbody tr:nth-child(1) a").click()
        
        # Esperar a que los comentarios estén visibles
        WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, ".post-box"))
        )
        
        # Verificar si hay al menos 1 comentario
        comments = self.driver.find_elements(By.CSS_SELECTOR, ".post-box")
        if len(comments) < 1:
            pytest.skip("No hay suficientes comentarios para borrar.")
        
        # Intentar hacer clic en el botón de borrar del primer comentario
        delete_button = self.driver.find_element(By.CSS_SELECTOR, ".post-box:nth-child(1) .btn")
        delete_button.click()
        
        # Esperar y aceptar el diálogo de confirmación
        WebDriverWait(self.driver, 10).until(EC.alert_is_present())
        alert = self.driver.switch_to.alert
        assert alert.text == "¿Estás seguro de que quieres borrar este post?"
        alert.accept()
        
        # Esperar a que el mensaje de éxito aparezca
        WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, ".alert-success"))
        )
        
    except Exception as e:
        pytest.fail(f"Test falló con excepción: {e}")
        
        
        
  ############################## TESTS RED SOCIAL SEGUIDOS Y SEGUIDORES ##############################

  def test_buscarusuario(self):
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.CSS_SELECTOR, "#top_user > .glyphicon").click()
    self.driver.find_element(By.LINK_TEXT, "Buscar usuarios").click()
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("lucia")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.LINK_TEXT, "lucia").click()
  
  def test_dejardeseguir(self):
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.CSS_SELECTOR, "#top_user > .glyphicon").click()
    self.driver.find_element(By.LINK_TEXT, "Ir al perfil").click()
    self.driver.find_element(By.LINK_TEXT, "Seguidos").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(2) .btn").click()
  
  def test_seguir(self):
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "top_user").click()
    self.driver.find_element(By.LINK_TEXT, "Buscar usuarios").click()
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("lucia")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary:nth-child(2)").click()
  
  def test_verseguidores(self):
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.CSS_SELECTOR, "#top_user > .glyphicon").click()
    self.driver.find_element(By.LINK_TEXT, "Ir al perfil").click()
    self.driver.find_element(By.LINK_TEXT, "Seguidores").click()
  
  def test_verseguidos(self):
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.CSS_SELECTOR, "#top_user > .glyphicon").click()
    self.driver.find_element(By.LINK_TEXT, "Ir al perfil").click()
    self.driver.find_element(By.LINK_TEXT, "Seguidos").click()
    
  
  
  ############################## TESTS RED SOCIAL MENSAJES ##############################
  
  def test_mandarmensaje(self):
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.CSS_SELECTOR, "#top_user > .glyphicon").click()
    self.driver.find_element(By.LINK_TEXT, "Ir al perfil").click()
    self.driver.find_element(By.LINK_TEXT, "Seguidos").click()
    self.driver.find_element(By.LINK_TEXT, "lucia").click()
    self.driver.find_element(By.LINK_TEXT, "Abrir Chat").click()
    
    self.driver.find_element(By.NAME, "content").click()
    self.driver.find_element(By.NAME, "content").send_keys("hola")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
  
  def test_mandar_y_borrar_mensaje(self):
    # Se debe iniciar sesión primero
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    # Navegar al perfil y abrir el chat
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.CSS_SELECTOR, "#top_user > .glyphicon").click()
    self.driver.find_element(By.LINK_TEXT, "Ir al perfil").click()
    self.driver.find_element(By.LINK_TEXT, "Seguidos").click()
    self.driver.find_element(By.LINK_TEXT, "lucia").click()
    self.driver.find_element(By.LINK_TEXT, "Abrir Chat").click()
    
    # Enviar un mensaje
    self.driver.find_element(By.NAME, "content").click()
    self.driver.find_element(By.NAME, "content").send_keys("hola")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    
    # Esperar y verificar que el mensaje se envió correctamente
    WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, ".message"))
    )
    
    messages = self.driver.find_elements(By.CSS_SELECTOR, ".message")
    assert len(messages) > 0, "No se encontraron mensajes en el chat."

    # Buscar el botón de borrar en el mensaje más reciente
    last_message = messages[-1]
    delete_button = last_message.find_element(By.CSS_SELECTOR, ".delete-button")
    delete_button.click()
    
    try:
      # Esperar a que el mensaje de éxito aparezca
      WebDriverWait(self.driver, 10).until(
          EC.presence_of_element_located((By.CSS_SELECTOR, ".alert-success"))
      )
      success_message = self.driver.find_element(By.CSS_SELECTOR, ".alert-success")
      assert "Mensaje eliminado." in success_message.text
      
    except Exception as e:
      pytest.fail(f"Test falló con excepción: {e}")  

  
  
  ############################## TESTS RED SOCIAL NOTIFICACIONES ##############################
  
  def test_notificacion_ver_mensaje(self):
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-bell").click()
    self.driver.find_element(By.LINK_TEXT, "Ver mensaje").click()
  
  def test_notificacion_ver_perfil(self):
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-bell").click()
    self.driver.find_element(By.LINK_TEXT, "Ver perfil").click()
  
  def test_notificacion_ver_post(self):
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-bell").click()
    self.driver.find_element(By.LINK_TEXT, "Ver post").click()
  
  def test_borrar_una_notificacion(self):
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-bell").click()
    
    notifications = self.driver.find_elements(By.CSS_SELECTOR, ".list-group-item")
    if len(notifications) == 0:
      pytest.skip("No quedan notificaciones para borrar.")
    
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(1) > form > .btn").click()
  
  def test_borrar_notificaciones(self):
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-bell").click()

    # Comprobar si hay notificaciones para eliminar
    notifications_present = len(self.driver.find_elements(By.CSS_SELECTOR, ".list-group-item")) > 0
    # Eliminar todas las notificaciones
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    assert self.driver.switch_to.alert.text == "¿Estás seguro de que quieres eliminar todas las notificaciones?"
    self.driver.switch_to.alert.accept()

    if notifications_present:
        WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, ".alert-success"))
        )
        success_message = self.driver.find_element(By.CSS_SELECTOR, ".alert-success").text
        assert success_message == "Todas las notificaciones han sido eliminadas."
    else:
        # Esperar a que el mensaje de error aparezca
        WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, ".alert-danger"))
        )
        error_message = self.driver.find_element(By.CSS_SELECTOR, ".alert-danger").text
        assert error_message == "No hay notificaciones para eliminar."
        
        
        
  ############################## TESTS AUDIOLIBRO ##############################
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_escuchar_y_parar_libro(self):
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1040)
    
    # Buscar libro "El gran Gatsby"
    self.driver.find_element(By.XPATH, "//img[@alt=\'El gran Gatsby\']").click()
    element = self.driver.find_element(By.XPATH, "//img[@alt=\'El gran Gatsby\']")
    
    # Mover el cursor al libro "El gran Gatsby"
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    
    # Mover el cursor al cuerpo de la página
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).move_by_offset(0, 0).perform()
    time.sleep(1)
    self.vars["window_handles"] = self.driver.window_handles
    
    # Abrir nueva ventana para el lector digital
    self.driver.find_element(By.ID, "readbtn").click()
    self.vars["win5834"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win5834"])
    self.driver.find_element(By.ID, "next").click()
    
    # Escuchar y parar audio
    self.driver.find_element(By.ID, "play-button").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "pause-button").click()
    time.sleep(1)
  
  
  def test_avanzar_audio(self):
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1040)
    
    # Buscar libro "El gran Gatsby"
    self.driver.find_element(By.XPATH, "//img[@alt=\'El gran Gatsby\']").click()
    element = self.driver.find_element(By.XPATH, "//img[@alt=\'El gran Gatsby\']")
    
    # Mover el cursor al libro "El gran Gatsby"
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    
    # Mover el cursor al cuerpo de la página
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).move_by_offset(0, 0).perform()
    time.sleep(1)
    self.vars["window_handles"] = self.driver.window_handles
    
    # Abrir nueva ventana para el lector digital
    self.driver.find_element(By.ID, "readbtn").click()
    self.vars["win5834"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win5834"])
    self.driver.find_element(By.ID, "next").click()
    
    # Reproducir audio
    self.driver.find_element(By.ID, "play-button").click()
    # Avanzar el progreso en la barra
    self.driver.find_element(By.ID, "progress-bar").send_keys("17")
    self.driver.find_element(By.ID, "progress-bar").click()
    # Continuar reproduciendo tras avanzar el progreso
    self.driver.find_element(By.ID, "play-button").click()
    time.sleep(1)
  
  
  def test_cambiar_capitulo(self):
    self.driver.get("http://localhost:8083/login?next=%2F")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "submit").click()
    
    self.driver.get("http://localhost:8083/")
    self.driver.set_window_size(974, 1040)
    
    # Buscar libro "El gran Gatsby"
    self.driver.find_element(By.XPATH, "//img[@alt=\'El gran Gatsby\']").click()
    element = self.driver.find_element(By.XPATH, "//img[@alt=\'El gran Gatsby\']")
    
    # Mover el cursor al libro "El gran Gatsby"
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    
    # Mover el cursor al cuerpo de la página
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).move_by_offset(0, 0).perform()
    time.sleep(1)
    self.vars["window_handles"] = self.driver.window_handles
    
    # Abrir nueva ventana para el lector digital
    self.driver.find_element(By.ID, "readbtn").click()
    self.vars["win684"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win684"])
    self.driver.find_element(By.ID, "next").click()
    
    # Obtener duración total del primer capítulo
    self.driver.find_element(By.ID, "play-button").click()
    time.sleep(1)
    total_time_chapter_1 = self.driver.find_element(By.ID, "total-time").text
    self.driver.find_element(By.ID, "pause-button").click()
    
    # Avanzar al siguiente capítulo
    self.driver.find_element(By.ID, "next").click()
    self.driver.find_element(By.ID, "next").click()
    self.driver.find_element(By.ID, "next").click()
    self.driver.find_element(By.ID, "next").click()
    self.driver.find_element(By.ID, "next").click()
    self.driver.find_element(By.ID, "next").click()
    
    # Obtener duración total del siguiente capítulo
    self.driver.find_element(By.ID, "play-button").click()
    time.sleep(1)
    total_time_chapter_2 = self.driver.find_element(By.ID, "total-time").text
    time.sleep(1)
    self.driver.find_element(By.ID, "pause-button").click()
    # Comparar los tiempos totales y hacer el assert
    assert total_time_chapter_1 != total_time_chapter_2, "El tiempo total no se ha recalculado al cambiar de capítulo."
    time.sleep(1)